### ISSUE TITLE
Declaration improvement

### ISSUE THREAD

**Issue by marekmalek** [lambdalisue/django-observer#1]
Hi,
I think this app is very useful to me but I made some improvements in observers declarations. I've prepared an ObserverMixin class which you can add to model as base class and define observers in Observers class as follow:

```
class Book(ObserverMixin, models.Model):
    name = models.CharField(max_length=255)

    class Observers:
        name = CallFunction('name_changed')

def name_changed(sender, obj, attr):
    print 'name changed'
```

My code also allow you to define instance method as callback function by using CallMethod('method_name') in observers declarations.

Source code:

<pre>
import inspect
import logging

from observer import watch
from django.db.models.base import ModelBase
from django.utils.importlib import import_module

log = logging.getLogger(__name__)

class ObserverModelBase(ModelBase):
    """
    Metaclass for models with observers.
    """
    def __new__(cls, name, bases, attrs):
        attr_observers = attrs.pop('Observers', None)
        new_class = super(ObserverModelBase, cls).__new__(cls, name, bases, attrs)
        if attr_observers:
            observers = inspect.getmembers(attr_observers, predicate=lambda a: isinstance(a, ObserverCallback))
            new_class.add_to_class('_observers', observers)
        return new_class

class ObserverCallback(object):
    def __init__(self, callback):
        self.callback = callback
        
class CallFunction(ObserverCallback):
    pass

class CallMethod(ObserverCallback):
    pass
    
class ObserverMixin(object):
    """
    Mixin to install observer on model attributes.
    """
    __metaclass__ = ObserverModelBase
    
    def save(self, *args, **kwargs):
        # install observers
        for attr_name, observer in self._observers:
            try:
                if isinstance(observer, CallMethod):
                    callback = getattr(self, observer.callback)
                elif isinstance(observer, CallFunction):
                    callback = observer.callback
                    if isinstance(callback, basestring):
                        # resolve callable from string
                        parts = callback.rsplit('.', 1)
                        if len(parts) > 1:
                            module = import_module(parts[0])
                            callback = getattr(module, parts[1])
                        else:
                            module = import_module(self.__module__)
                            callback = getattr(module, parts[0])
                else:
                    callback = None
            except Exception, e:
                log.exception(e)
                callback = None
                
            if callback:
                watch(self, attr_name, callback)
            else:
                log.warning('Unable to resolve callback for: %s in %s', attr_name, self.__class__)
        return super(ObserverMixin, self).save(*args, **kwargs)
</pre>

**Comment by lambdalisue** [comment]
Cool. I like your idea. Would you add the following codes and send me a pull request?

``` python
class ObserverMixin(object):
    """
    Mixin to install observer on model attributes.
    """
    __metaclass__ = ObserverModelBase

    def save(self, *args, **kwargs):
        created = self.pk is None
        if created:
            # prevent re-registration
            self._register_watchers()
        return super(ObserverMixin, self).save(*args, **kwargs)

    def _register_watchers(self):
        # install observers
        for attr_name, observer in self._observers:
            try:
                if isinstance(observer, CallMethod):
                    callback = getattr(self, observer.callback)
                elif isinstance(observer, CallFunction):
                    callback = observer.callback
                    if isinstance(callback, basestring):
                        # resolve callable from string
                        parts = callback.rsplit('.', 1)
                        if len(parts) > 1:
                            module = import_module(parts[0])
                            callback = getattr(module, parts[1])
                        else:
                            module = import_module(self.__module__)
                            callback = getattr(module, parts[0])
                else:
                    callback = None
            except Exception, e:
                log.exception(e)
                callback = None

            if callback:
                watch(self, attr_name, callback)
            else:
                log.warning('Unable to resolve callback for: %s in %s', attr_name, self.__class__)
```

Registration should be happen once for each instance so I add checking code. I'm sorry that my sample code in README does not check :-(

**Comment by marekmalek** [comment]
Thanks for the feedback but in your case watchers are installed only for newly created instances. In most cases we need them for updating objects.
My proposition is to add watchers instances to self._registered_watchers attribute and filter them out while registration.

``` python
class ObserverMixin(object):
    """
    Mixin to install observer on model attributes.
    """
    __metaclass__ = ObserverModelBase
    _registered_watchers = None

    def save(self, *args, **kwargs):
        # prevent re-registration
        self._register_watchers()
        return super(ObserverMixin, self).save(*args, **kwargs)

    def _not_registered_observers(self):
        watched_attrs = map(lambda watcher: watcher._attr, self._registered_watchers)
        return filter(lambda (attr, observer): attr not in watched_attrs, self._observers)

    def _register_watchers(self):
        if self._registered_watchers is None:
            self._registered_watchers = []
        # install observers
        for attr_name, observer in self._not_registered_observers():
            try:
                if isinstance(observer, CallMethod):
                    callback = getattr(self, observer.callback)
                elif isinstance(observer, CallFunction):
                    callback = observer.callback
                    if isinstance(callback, basestring):
                        # resolve callable from string
                        parts = callback.rsplit('.', 1)
                        if len(parts) > 1:
                            module = import_module(parts[0])
                            callback = getattr(module, parts[1])
                        else:
                            module = import_module(self.__module__)
                            callback = getattr(module, parts[0])
                else:
                    callback = None
            except Exception, e:
                log.exception(e)
                callback = None

            if callback:
                self._registered_watchers.append(watch(self, attr_name, callback))
                observer.registered = True
            else:
                log.warning('Unable to resolve callback for: %s in %s', attr_name, self.__class__)
```

I'll send you a pull request with complete code.

**Comment by lambdalisue** [comment]
True, true. Sorry I wrote this plugin long time ago so I don't remember how and why...

Actually I'm not sure that **why we don't write a registration code in constructor**. If we can write that in constructor, things get much better. Current registration code only let observing an instance which **saved at least once after the server start** so as you said non newly created instance is not observed completely.

Now I don't have enough time to check these things so would you check whether the registration code in `__init__` method works or not? like

``` python
class ObserverMixin(object):
    """
    Mixin to install observer on model attributes.
    """
    __metaclass__ = ObserverModelBase

    def __init__(self, *args, **kwargs):
        super(ObserverMixin, self).__init__(*args, **kwargs)
        # install observers
        self._register_watchers()

    def _register_watchers(self):
        for attr_name, observer in self._observers:
            try:
                if isinstance(observer, CallMethod):
                    callback = getattr(self, observer.callback)
                elif isinstance(observer, CallFunction):
                    callback = observer.callback
                    if isinstance(callback, basestring):
                        # resolve callable from string
                        parts = callback.rsplit('.', 1)
                        if len(parts) > 1:
                            module = import_module(parts[0])
                            callback = getattr(module, parts[1])
                        else:
                            module = import_module(self.__module__)
                            callback = getattr(module, parts[0])
                else:
                    callback = None
            except Exception, e:
                log.exception(e)
                callback = None

            if callback:
                observer.watcher = watch(self, attr_name, callback)
            else:
                log.warning('Unable to resolve callback for: %s in %s', attr_name, self.__class__)
```

**Comment by marekmalek** [comment]
Well we could but we don't need to because not every initialized object have to be saved so in that case we don't need to observe it.

**Comment by lambdalisue** [comment]
Thank you for sending me a pull request and response. Hum... then what about the instance which is already saved in db like...
1. Save an instance to the database. This time, observing works correctly.
2. Stop the server.
3. Restart the server. I guess in this time, `save` method of saved instance is not called so present instance is not observing

But as you said, not every initialized object have to be saved so it might be complecated.

**Comment by marekmalek** [comment]
It's not an issue because observers are installed in save method before you call super() so in situation you described:
1. Initialize instance
2. Modify instance
3. Call save()
4. Observer is installed
5. Pre-save signal handled and not saved instance loaded from db
6. Post-save signal handled and values are compared

btw. I didn't analyse whole code so can you tell me when observer is unloaded?

**Comment by marekmalek** [comment]
Maybe I'm wrong with understanding how your app is working but I thought it can be used in following pattern:
1. Init object - don't set any signal receivers
2. Modify instance
3. Call save() - this is the place where we want to know whether instance was modified
   - install observer and initialize pre_save and post_save signal handlers
   - detect whether object was modified as it is now in pre_save and post_save handlers
   - remove observer

That way we keep clean list of signal receivers because we install them only when object is being saved and removed them right after that.

Updated mixin to remove receivers:

``` python
class ObserverMixin(object):
    """
    Mixin to install observer on model attributes.
    """
    __metaclass__ = ObserverModelBase
    _registered_watchers = None

    def save(self, *args, **kwargs):
        # register watchers
        self._register_watchers()
        try:
            super(ObserverMixin, self).save(*args, **kwargs)
        finally:
            self._unregister_watchers()

    def _not_registered_observers(self):
        watched_attrs = map(lambda watcher: watcher._attr, self._registered_watchers)
        return filter(lambda (attr, observer): attr not in watched_attrs, self._observers)

    def _register_watchers(self):
        if self._registered_watchers is None:
            self._registered_watchers = []
        # install observers
        for attr_name, observer in self._not_registered_observers():
            try:
                if isinstance(observer, CallMethod):
                    callback = getattr(self, observer.callback)
                elif isinstance(observer, CallFunction):
                    callback = observer.callback
                    if isinstance(callback, basestring):
                        # resolve callable from string
                        parts = callback.rsplit('.', 1)
                        if len(parts) > 1:
                            module = import_module(parts[0])
                            callback = getattr(module, parts[1])
                        else:
                            module = import_module(self.__module__)
                            callback = getattr(module, parts[0])
                else:
                    callback = None
            except Exception, e:
                log.exception(e)
                callback = None

            if callback:
                self._registered_watchers.append(watch(self, attr_name, callback))
            else:
                log.warning('Unable to resolve callback for: %s in %s', attr_name, self.__class__)

    def _unregister_watchers(self):
        try:
            while True:
                watcher = self._registered_watchers.pop()
                watcher.unwatch()
        except IndexError:
            pass
```

**Comment by lambdalisue** [comment]
Well, this library use django signals to check field change, that's mean you don't have to call `watch` method everytime.

A simple example is

``` python
class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()

def title_changed(sender, obj, attr, **kwargs):
    print "title changed"

article = Article.objects.create(title='foo', body='bar')

article.title = "hello"
article.save()
# >> title_changed is not called

# install observer
article._watcher = watch(article, 'title', title_changed)

article.title = "hello"
article.save()
# >> title_changed is not called because title doesn't changed

article.title = "changed"
article.save()
# >> title_changed is called
```

And also, there are `ModelWatcher` so **calling the `save` method of the instance is not required to fire the watcher callback sometimes**

``` python
class Parent(models.Model):
    name = models.CharField(max_length=100)

class Child(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey(Parent, related_name='children')

parent = Parent.objects.create(name='foo')
child1 = Child.objects.create(name='1', parent=parent)
child2 = Child.objects.create(name='2', parent=parent)
child3 = Child.objects.create(name='3', parent=parent)

def name_changed(sender, obj, attr, **kwargs):
    print "name changed"
def children_changed(sender, obj, attr, **kwargs):
    print "children changed"
def name_changed_child1(sender, obj, attr, **kwargs):
    print "name of child1 changed"
def name_changed_child2(sender, obj, attr, **kwargs):
    print "name of child2 changed"
def name_changed_child3(sender, obj, attr, **kwargs):
    print "name of child3 changed"
def parent_changed_child1(sender, obj, attr, **kwargs):
    print "parent of child1 changed"
def parent_changed_child2(sender, obj, attr, **kwargs):
    print "parent of child2 changed"
def parent_changed_child3(sender, obj, attr, **kwargs):
    print "parent of child3 changed"

# install observers
parent._watcher1 = watch(parent, 'name', name_changed)
parent._watcher2 = watch(parent, 'children', children_changed)
child1._watcher1 = watch(child1, 'name', name_changed_child1)
child1._watcher2 = watch(child1, 'parent', parent_changed_child1)
child2._watcher1 = watch(child2, 'name', name_changed_child2)
child2._watcher2 = watch(child2, 'parent', parent_changed_child2)
child3._watcher1 = watch(child3, 'name', name_changed_child3)
child3._watcher2 = watch(child3, 'parent', parent_changed_child3)

parent.name = 'foo'
parent.save()
# >> Nothing happen

parent.name = 'bar'
parent.save()
# >> name_changed, parent_changed_child1-3 is called
#
# Note:
#   parent_changed_child1-3 is called even `save` method of child1-3 was not called.
#   In this case, if observer registration code was in `save` method, this type of
#   callback will be not called because the observer hadn't been installed when parent was changed.
#
```

**Comment by marekmalek** [comment]
Yep, that's clear but I can see a possible inefficiency in the way you register watcher's signals. Because each watcher is installed per model instance so each instance will register it's own pre_save, post_save signals handlers. 
Assuming I want to observe instances of model Child, I have to install watcher per every instance:

``` python
child1._watcher1 = watch(child1, 'name', name_changed_child1)
child2._watcher1 = watch(child2, 'name', name_changed_child2)
```

If you call save() on one of the instance, all signal handlers will be run:
- pre_save for child1
- pre_save for child2

Because you don't remove observers those signal handlers exists for the whole lifetime of program so it's easy to imagine that their number can increase significantly.
What I suggested to overcome this was to install observer only when object is being saved and remove it after that. That way we keep handlers list clean and it won't grow over lifetime. You can investigate it by listing post_save signal receivers list:

``` python
from django.db.models.signals import post_save
print 'post save receivers: ', post_save.receivers
```

Another approach (but it requires more changes in your implementation) is to install only 1 observer per model and not per each instance. It's feasible because you don't need instance of object when you initialize Watcher. You just need to know model class (to bind signals) and attribute to observe. Instance of object you will get in pre_save, post_save signal.

Does it make sense to you?

**Comment by lambdalisue** [comment]
> each watcher is installed per model instance so each instance will register it's own pre_save, post_save signals handlers.

Oh yeah, I didn't really think about it thanks :-)
Well currently the receiver code filter the instance via the pk value of the stored target instance so what I need to do might be
(Ref: https://github.com/lambdalisue/django-observer/blob/master/observer/watchers/model.py#L56)
1. Remove signal registration codes from `__init__`
2. Register signals with `post_sync` or whatever which called only once
3. Filter the signals with `isinstance(instance) == model` in each receiver codes

In this modification, the usage does not change I guess. Still what you need is call `watch` method with an instance which you want to observe.
However, I'm not really sure that it's a good way to do it because checking all signals of `post_save` or whatever might slow the codes (but even so, much better than current one)

What do you think about this?

**Comment by marekmalek** [comment]
Yes, removing signals registration from watcher's `__init__` is a good idea but we can't register them on post_sync because it's not called every time program starts.
My suggestion is :
1. Create a mechanism to register instance watchers (I think my mixin can be very helpful here) and store them in instance attribute
2. If first watcher is registered then register signals handlers - but it's very important to do it only once per Model
3. pre_save and post_save handlers iterates over stored watchers and call watcher's signal handler

Following code is just a mockup but I hope you'll catch what I mean:

``` python
class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()

def title_changed(sender, obj, attr, **kwargs):
    print "title changed"

def body_changed(sender, obj, attr, **kwargs):
    print "body changed"

article = Article.objects.create(title='foo', body='bar')

# install observers
article._watcher1 = watch(article, 'title', title_changed)
article._watcher2 = watch(article, 'body', body_changed)

# register signals handlers once
def pre_save_receiver(sender, instance, **kwargs):
    # iterate over all instance watchers and call signal receivers
    article._watcher1._pre_save_reciver(sender, instance, **kwargs)
    article._watcher2._pre_save_reciver(sender, instance, **kwargs)
pre_save.connect(pre_save_receiver, sender=Article)

def post_save_receiver(sender, instance, **kwargs):
    # iterate over all instance watchers and call signal receivers
    article._watcher1._post_save_reciver(sender, instance, **kwargs)
    article._watcher2._post_save_reciver(sender, instance, **kwargs)
post_save.connect(post_save_receiver, sender=Article)
```
