### ISSUE TITLE
README.rst is missing

### ISSUE THREAD

**Issue by philippeowagner** [lambdalisue/django-observer#3]
I tried to install the package from PyPI, but the README is missing.

IOError: [Errno 2] No such file or directory: '/var/www/xxx.com/dev/build/django-observer/README.rst'

I installed directly from GitHub, but for production an installable package from PyPI is indispensable. Could you fix that and push a new version to PyPI? Thanks in advance.

**Comment by lambdalisue** [comment]
Ok I'll fix it. Thanks for the report.

**Comment by lambdalisue** [comment]
Ok I did. Now [PyPI](https://pypi.python.org/pypi/django-observer/) version is updated to 0.4.3 and have `README.rst`. Thanks again fot the report.

**Comment by philippeowagner** [comment]
@lambdalisue thank you.
