### ISSUE TITLE
Re-registration of watch not working after server restart.

### ISSUE THREAD

**Issue by philippeowagner** [lambdalisue/django-observer#6]
Sadly #5 does not fix #4 as expected. After restarting the server (django instance) the watcher is not active anymore. I assume that his is the reason to reconnect it in every `save()` call. 
There must be a mechanism to re-connect and ensures that the same watcher is only called/triggered once. 

@lambdalisue what do you think?

**Comment by philippeowagner** [comment]
After digging a bit around I have a few questions and thoughts:
- Because the linked watcher is not persistent suggestion #5 is useless. Sorry about that.
- Testing against `_watcher` with `getattr(self, '_watcher', False)` would be a better idea because the watcher has to be linked and linked again. 
- The first change gets lost (by design?) because the object has to be saved before the watcher can be linked to the object itself. 
- Not sure if it's just me .. but, is there a working example using django-observer?

**Comment by lambdalisue** [comment]
Ok, give me a time to dig the principle of the plugin.

**Comment by lambdalisue** [comment]
Ah, I have totally forgot about this pull. https://github.com/lambdalisue/django-observer/pull/2
The mixin would help your situation I guess.

**Comment by lambdalisue** [comment]
I got the point, but it is quite difficult to solve with current strategy thus i'm writing new version.

**Comment by philippeowagner** [comment]
Hi @lambdalisue 
Thanks for getting back and confirming the issues. Never mind, we will move on and find another solution for our current project.
